[phases.backend]
nixPkgs = ["nodejs"]
cmds = [
    "cd backend && npm install",
    "cd backend && npm run build --if-present"
]

[phases.frontend]
nixPkgs = ["nodejs"]
cmds = [
    "cd frontend && npm install --if-present",
    "cd frontend && npm run build --if-present"
]

[start]
cmd = "cd backend && node server.js"